Repository ublue-os/bluefin, pull requests merged in 2024-07, with the labels that each got.

#1470 style: Standardize FromAsCasing in dockerfile
  Containerfile
Labels: lgtm, size:XS

#1475 feat(dx): add monaspace font
  build_files/dx/build-dx.sh
  build_files/dx/fonts-dx.sh
Labels: dx, lgtm, size:S

#1483 refactor: update cosign public key
  cosign.pub
Labels: lgtm, size:XS

#1492 fix: update gnome-vrr copr
  build_files/base/copr-repos.sh
Labels: lgtm, size:XS

#1477 feat: ujust command to toggle Tailscale
  just/bluefin-system.just
Labels: enhancement, lgtm, size:M

#1499 chore(ci): bluefin latest fedora version
  .github/workflows/build-bluefin-latest-iso.yml
Labels: github_actions, lgtm, size:XS

#1503 feat: remove bluefin-cli shortcut
  system_files/silverblue/usr/etc/dconf/db/local.d/01-ublue
Labels: brew, lgtm, size:XS

#1502 feat: Use Cached Kernel, fsync for latest
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/base/build-base.sh
  build_files/base/cache_kernel.sh
  build_files/base/coreos_kernel.sh
  build_files/base/install-akmods.sh
  build_files/base/nvidia.sh
  build_files/shared/image-info.sh
  scripts/build-image.sh
Labels: github_actions, lgtm, size:L

#1507 fix: correct zfs install
  build_files/base/install-akmods.sh
Labels: size:XS

#1512 feat: add umoci for incus container support
  build_files/dx/cleanup-dx.sh
  build_files/dx/copr-repos-dx.sh
  packages.json
Labels: dx, lgtm, size:XS

#1513 refactor: use akmods-zfs for ZFS install
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/base/install-akmods.sh
  build_files/dx/install-akmods-dx.sh
  scripts/build-image.sh
Labels: github_actions, lgtm, size:M

#1514 feat(just): Add descriptions to rebase-helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: enhancement, lgtm, size:XS

#1518 feat: move utilities into the utility folder
  system_files/silverblue/usr/etc/dconf/db/local.d/02-bluefin-folders
Labels: enhancement, lgtm, size:XS

#1516 feat: add opendyslexic font
  packages.json
Labels: enhancement, lgtm, size:XS

#1519 fix: add skopeo to devcontainer's features
  .devcontainer/devcontainer.json
Labels: dependencies, lgtm, size:XS

#1522 chore(ci): explicitly use v1.2.1 for ISO action
  .github/workflows/reusable-build-iso.yml
Labels: lgtm, size:XS

#1523 feat: switch to distro ptyxis for F40
  build_files/base/copr-repos.sh
  packages.json
Labels: enhancement, lgtm, size:S

#1524 fix(just): remind user to run dx-group
  just/bluefin-system.just
Labels: dx, lgtm, size:XS

#1530 feat: add bpftop
  packages.json
Labels: enhancement, lgtm, size:XS

#1525 chore(ci): speedup builds with cache mount
  Containerfile
  build_files/aurora-changes.sh
  build_files/base/build-base.sh
  build_files/bluefin-changes.sh
  build_files/bootc.sh
  build_files/branding-dx.sh
  build_files/branding.sh
  build_files/brew.sh
  build_files/build-base.sh
  build_files/build-dx.sh
  build_files/cache_kernel.sh
  build_files/clean-stage.sh
  build_files/cleanup-dx.sh
  build_files/cleanup.sh
  build_files/copr-repos-dx.sh
  build_files/copr-repos.sh
  build_files/dx/build-dx.sh
  build_files/fetch-install-dx.sh
  build_files/fetch-install.sh
  build_files/fetch-quadlets.sh
  build_files/firmware.sh
  build_files/font-install.sh
  build_files/fonts-dx.sh
  build_files/image-info.sh
  build_files/initramfs.sh
  build_files/install-akmods-dx.sh
  build_files/install-akmods.sh
  build_files/nvidia.sh
  build_files/packages-dx.sh
  build_files/packages.sh
  build_files/systemd-dx.sh
  build_files/systemd.sh
  build_files/workarounds.sh
Labels: dx, lgtm, size:L

#1533 fix: update project documentation link
  system_files/shared/usr/share/applications/Documentation.desktop
Labels: documentation, lgtm, size:XS

#1535 Added new dinosaur logos for fastfetch
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/ducky.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/luke.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/runner.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/ducky
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/luke
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/runner
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/ducky
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/luke
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/runner
Labels: enhancement, size:L

#1539 fix: update secureboot password
  .github/workflows/reusable-build-iso.yml
  README.md
  scripts/build-iso-ghcr.sh
  scripts/build-iso-installer-main.sh
  scripts/build-iso.sh
Labels: iso, lgtm, size:S

#1537 chore: clean up vestigial flatpaks
  system_files/kinoite/usr/etc/flatpak/system/install
  system_files/kinoite/usr/etc/flatpak/system/remove
  system_files/kinoite/usr/etc/flatpak/user/install
  system_files/kinoite/usr/etc/flatpak/user/remove
  system_files/silverblue/usr/etc/flatpak/system/install
  system_files/silverblue/usr/etc/flatpak/system/remove
  system_files/silverblue/usr/etc/flatpak/user/install
  system_files/silverblue/usr/etc/flatpak/user/remove
Labels: lgtm, size:M

#1545 chore: packages.json: Remove kdeplasma-addons (already included)
  .github/pull_request_template.md
  packages.json
Labels: documentation, lgtm, size:XS

#1544 feat: add rocm-smi
  packages.json
Labels: enhancement, lgtm, size:XS

#1540 feat(just): add switch-channel shortcut
  just/bluefin-system.just
Labels: enhancement, lgtm, size:XS

#1549 Add shellcheck via brew
  system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: brew, lgtm, size:XS
