Repository ublue-os/bluefin, pull requests merged in 2024-09, with the labels that each got.

#1640 fix: limited linesize to 78 characters to accomodate 80x24 terminal
  system_files/shared/usr/libexec/ublue-motd
Labels: bug, lgtm, size:XS

#1649 feat: add git-credential-libsecret to DX
  packages.json
Labels: dx, lgtm, size:XS

#1654 fix(aurora): update KDE settings homepage link
  system_files/kinoite/usr/share/kde-settings/kde-profile/default/xdg/kcm-about-distrorc
Labels: aurora, lgtm, size:XS

#1659 fix(bluefin-tools): Don't explicitly start ollama after creating service
  just/bluefin-tools.just
Labels: bug, lgtm, size:XS

#1667 feat: add performance tools
  packages.json
Labels: enhancement, lgtm, size:XS

#1671 fix(just): remove configure-shell
  just/bluefin-system.just
Labels: bug, lgtm, size:S

#1673 feat(gnome): Set animation speed to .8
  system_files/silverblue/etc/environment
Labels: enhancement, lgtm, size:XS

#1674 feat: add active directory support
  packages.json
Labels: enhancement, lgtm, size:XS

#1680 chore(readme): remove broken aurora badges from readme
  README.md
Labels: lgtm, size:XS

#1681 feat: add scx-scheds
  packages.json
Labels: enhancement, lgtm, size:XS

#1682 fix: remove nonexistant libsssd_sudo package
  packages.json
Labels: bug, lgtm, size:XS

#1688 fix: enable incus-startup service
  system_files/dx/usr/libexec/bluefin-incus
Labels: dx, lgtm, size:XS

#1693 feat: add Discourse desktop shortcut
  system_files/shared/usr/share/applications/Discourse.desktop
  system_files/shared/usr/share/ublue-os/bluefin/discourse.svg
Labels: enhancement, size:XS

#1661 feat: Add notification for secure boot key check
  build_files/systemd.sh
  system_files/kinoite/usr/share/ublue-os/motd/bluefin.md
  system_files/shared/etc/profile.d/sb-key-notify-autostart.sh
  system_files/shared/etc/skel/.config/autostart/sb-key-notify.desktop
  system_files/shared/usr/bin/sb-key-notify
  system_files/shared/usr/lib/systemd/system/check-sb-key.service
  system_files/shared/usr/libexec/check-sb-key.sh
  system_files/shared/usr/libexec/ublue-motd
  system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
Labels: enhancement, lgtm, size:M

#1687 feat: rechunk images into smaller parts
  .github/workflows/build-latest-aurora.yml
  .github/workflows/build-latest-bluefin.yml
  .github/workflows/reusable-build.yml
Labels: enhancement, size:M

#1697 fix(ci): update rechunk action inputs
  .github/workflows/reusable-build.yml
Labels: github_actions, size:XS

#1699 fix: update warning formatting
  system_files/shared/usr/libexec/check-sb-key.sh
  system_files/shared/usr/libexec/ublue-motd
Labels: bug, size:XS

#1700 chore(ci): temporarily disable rechunk in latest
  .github/workflows/build-latest-aurora.yml
  .github/workflows/build-latest-bluefin.yml
Labels: github_actions, size:XS

#1698 fix(ci): switch to rootful podman build
  .github/workflows/build-latest-aurora.yml
  .github/workflows/build-latest-bluefin.yml
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:L

#1695 fix(just): fix rebase-helper aliases
  just/bluefin-system.just
Labels: bug, lgtm, size:XS

#1705 feat(framework): add color profile for the new fw13 screen
  system_files/shared/usr/share/color/icc/colord/framework13.icc
Labels: framework, lgtm, size:XS

#1708 feat: Add os-release changes from Bazzite
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/copr-repos.sh
  build_files/image-info.sh
Labels: enhancement, lgtm, size:M

#1714 fix: Correct doubled build ID in DX images
  Containerfile
Labels: dx, lgtm, size:XS

#1713 chore(bluefin): update GNOME application groups
  system_files/silverblue/etc/dconf/db/local.d/02-bluefin-folders
Labels: enhancement, lgtm, size:S

#1709 feat: fix weird titlebar on chromium
  system_files/kinoite/etc/skel/.config/gtk-3.0/gtk.css
Labels: bug, size:XS

#1710 fix: rename discourse shortcut to community
  system_files/shared/usr/share/applications/Discourse.desktop
Labels: lgtm, size:XS

#1720 feat(bluefin-cli): add trash-cli
  system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: documentation, enhancement, lgtm, size:XS

#1724 fix: ensure gnome-extensions-app is removed
  build_files/packages-dx.sh
  build_files/packages.sh
Labels: bug, lgtm, size:M
