Repository ublue-os/bluefin, pull requests merged in 2024-11, with the labels that each got.

#1861 feat: make podman-machine work by default OOB
  packages.json
Labels: enhancement, lgtm, size:XS

#1857 fix(framework): turn the framework akmod back on
  build_files/install-akmods.sh
Labels: framework, lgtm, size:XS

#1884 chore: fix name of Latest ISO workflow
  .github/workflows/build-image-latest.yml
Labels: github_actions, lgtm, size:XS

#1887 chore(ci): fix stable-daily image signing
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:XS

#1888 chore(ci): stable-daily run on merge-group
  .github/workflows/build-image-beta.yml
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/generate_changelog.yml
Labels: github_actions, lgtm, size:M

#1891 chore(ci): fix typos in generate-release workflow
  .github/workflows/generate-release.yml
Labels: github_actions, lgtm, size:XS

#1893 chore(ci): cosign signing for legacy hwe support
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:S

#1871 fix: remove redundant fc-cache run on ublue-user-update service
  system_files/shared/usr/libexec/ublue-user-setup
Labels: lgtm, size:XS

#1877 feat: add k8s-dev-tools to ujust directly on bluefin
  just/bluefin-tools.just
Labels: enhancement, lgtm, size:XS

#1883 chore: remove explicit tap-to-click since its already set by default in f40
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: lgtm, size:S

#1904 chore(ci): fix build-iso workflow/justfile
  .github/workflows/reusable-build-iso.yml
  Justfile
Labels: github_actions, lgtm, size:XS

#1908 chore: remove references to deprecated bluefin-cli container
  build_files/base/06-fetch-quadlets.sh
  just/bluefin-system.just
  system_files/kinoite/usr/share/applications/quadlet-bluefin.desktop
  system_files/kinoite/usr/share/kglobalaccel/quadlet-bluefin.desktop
  system_files/shared/usr/libexec/configure-terminal.sh
  system_files/shared/usr/libexec/enable-bluefin-cli.sh
  system_files/shared/usr/libexec/ptyxis-create-profile.sh
  system_files/shared/usr/share/ublue-os/bluefin-cli/known-containers
Labels: lgtm, size:L

#1876 feat: ensure firefox (flatpak) has hardware decoding turned on by default
  system_files/shared/usr/libexec/ublue-flatpak-manager
  system_files/shared/usr/share/ublue-os/firefox-config/01-bluefin-global.js
Labels: enhancement, lgtm, size:S

#1911 fix: WEBUI to WEB_UI
  Justfile
Labels: bug, lgtm, size:XS

#1917 chore(hwe): 09-hwe-additions.sh
  build_files/base/09-hwe-additions.sh
Labels: lgtm, size:S

#1916 chore(just): restrict topgrade to only supported things
  system_files/shared/usr/share/ublue-os/topgrade.toml
Labels: lgtm, size:XS

#1919 fix: stable tag on schedule
  .github/workflows/build-image-beta.yml
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/reusable-build.yml
Labels: bug, github_actions, lgtm, size:S

#1910 chore(ci): Consolidate workflow into just commands
  .github/changelogs.py
  .github/workflows/build-image-beta.yml
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/generate-release.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  Justfile
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/05-override-install.sh
  build_files/base/06-fetch-quadlets.sh
  build_files/base/07-base-image-changes.sh
  build_files/base/08-firmware.sh
  build_files/base/09-hwe-additions.sh
  build_files/base/10-brew.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/04-override-install-dx.sh
Labels: dx, github_actions, lgtm, size:XXL

#1920 chore(ci): clean changelog/Workflow
  .github/changelogs.py
  .github/workflows/build-image-stable.yml
  .github/workflows/generate-release.yml
  .github/workflows/reusable-build.yml
  .gitignore
  Justfile
  build_files/base/03-install-kernel-akmods.sh
Labels: github_actions, lgtm, size:L

#1921 feat: enable kernel_pin and pin kernel for stable/gts
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/reusable-build.yml
  Justfile
Labels: github_actions, lgtm, size:S

#1923 fix: CI fixes for ISO/Changelogs
  .github/changelogs.py
  .github/workflows/reusable-build-iso.yml
  Justfile
Labels: github_actions, lgtm, size:M

#1928 chore(ci): fix iso names for cloudflare bucket
  .github/workflows/build-iso-latest.yml
  .github/workflows/generate-release.yml
  .github/workflows/reusable-build-iso.yml
  Justfile
Labels: lgtm, size:S

#1937 fix: changelogs only need 2 tags
  .github/changelogs.py
Labels: size:XS

#1935 chore: update issue template to bootc
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: lgtm, size:XS

#1934 fix: deprecate playerctl
  packages.json
Labels: lgtm, size:XS

#1938 fix(ci): correct weekly schedule trigger
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/generate-release.yml
Labels: github_actions, lgtm, size:XS

#1902 feat: automatically use bootc to update system if locklayering is being used
  just/bluefin-system.just
  system_files/shared/usr/share/ublue-os/just/10-update.just
  system_files/shared/usr/share/ublue-os/topgrade-bootc.toml
Labels: enhancement, lgtm, size:S

#1940 chore(topgrade): make it so topgrade-bootc follows allowlist pattern
  system_files/shared/usr/share/ublue-os/topgrade-bootc.toml
Labels: lgtm, size:XS

#1914 chore(just): clean up ujust recipes to fit newer style
  just/bluefin-apps.just
  just/bluefin-system.just
  just/bluefin-tools.just
  system_files/dx/usr/libexec/bluefin-incus
  system_files/shared/usr/share/ublue-os/just/10-update.just
Labels: lgtm, size:XL

#1950 chore(yafti): remove remaining yafti files
  system_files/shared/etc/profile.d/bluefin-firstboot.sh
  system_files/shared/etc/skel/.config/autostart/bluefin-firstboot.desktop
  system_files/shared/etc/yafti.yml
Labels: lgtm, size:L

#1951 chore(f39): remove vestigial f39 reference in packages.json
  packages.json
Labels: lgtm, size:S

#1942 feat: update motd tips
  system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
Labels: enhancement, lgtm, size:XS

#1957 fix: correct iso name for run-iso
  Justfile
Labels: iso, lgtm, size:XS

#1949 chore(just): remove AI integration from ujust
  just/bluefin-apps.just
  just/bluefin-tools.just
  system_files/dx/usr/share/ublue-os/distrobox/pytorch-nvidia.ini
Labels: lgtm, size:L

#1959 fix: pin pkcs11-provider to 0.5-3.fc41
  build_files/base/18-workarounds.sh
Labels: bug, lgtm, size:XS

#1960 chore: add pin package issue template
  .github/ISSUE_TEMPLATE/pin.yml
Labels: size:S

#1901 chore: purge all the default container configuration
  build_files/base/06-fetch-quadlets.sh
  build_files/shared/build-base.sh
  just/bluefin-system.just
  system_files/kinoite/usr/share/applications/quadlet-fedora.desktop
  system_files/kinoite/usr/share/applications/quadlet-ubuntu.desktop
  system_files/kinoite/usr/share/kglobalaccel/quadlet-fedora.desktop
  system_files/kinoite/usr/share/kglobalaccel/quadlet-ubuntu.desktop
  system_files/shared/usr/libexec/configure-terminal.sh
  system_files/shared/usr/libexec/distrobox-quadlet-ptyxis.sh
  system_files/shared/usr/libexec/ptyxis-create-profile.sh
  system_files/shared/usr/share/ublue-os/bluefin-cli/known-containers
  system_files/shared/usr/share/ublue-os/bluefin-cli/known-ptyxis-profiles
  system_files/shared/usr/share/ublue-os/bluefin-cli/ptyxis-integration
  system_files/shared/usr/share/ublue-os/quadlets/podmansh.container
  system_files/silverblue/etc/dconf/db/distro.d/02-bluefin-keybindings
Labels: lgtm, size:L

#1962 feat(dx): add bootc tooling
  build_files/dx/01-install-copr-repos-dx.sh
  packages.json
Labels: enhancement, dx, lgtm, size:XS

#1948 chore(ptyxis): remove profile integration ootb
  system_files/shared/usr/libexec/ptyxis-add-profile.sh
  system_files/shared/usr/libexec/ptyxis-create-profile.sh
  system_files/shared/usr/libexec/ptyxis-remove-profile.sh
  system_files/shared/usr/share/ublue-os/bluefin-cli/known-ptyxis-profiles
  system_files/silverblue/etc/dconf/db/distro.d/02-bluefin-keybindings
Labels: lgtm, size:L

#1944 feat(sddm): add mount unit for installing sddm themes in Discover
  build_files/base/07-base-image-changes.sh
  system_files/kinoite/usr/lib/systemd/system/usr-share-sddm-themes.mount
  system_files/kinoite/usr/lib/tmpfiles.d/usr-share-ssdm-themes.conf
Labels: enhancement, lgtm, size:S

#1968 fix(ujust): dx detection on nvidia/surface/others
  just/bluefin-apps.just
  just/bluefin-system.just
Labels: dx, lgtm, size:XS

#1961 chore(ci): add 90 day cleanup action
  .github/workflows/clean.yml
Labels: github_actions, lgtm, size:S

#1973 fix(sddm): Use default permissions for themes directories
  system_files/kinoite/usr/lib/tmpfiles.d/usr-share-ssdm-themes.conf
Labels: bug, lgtm, size:XS

#1974 fix(ujust): dx-group using built in GROUPS array in bash
  just/bluefin-system.just
Labels: dx, lgtm, size:XS

#1969 chore(ci): add remaining images for cleanup
  .github/workflows/clean.yml
Labels: github_actions, lgtm, size:XS

#1978 feat: set mutter experimental kms-modifiers for nvidia
  build_files/base/07-base-image-changes.sh
  just/bluefin-system.just
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, lgtm, size:M

#1985 chore: remove 'ujust ollama' from motd tips
  system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
Labels: size:XS

#1983 chore: show nvidia version in changelog
  .github/changelogs.py
Labels: enhancement, lgtm, size:XS

#1874 feat(just): add brew-command-not-found setup
  just/bluefin-apps.just
Labels: brew, lgtm, size:M

#1986 feat: add december wallpapers
  system_files/silverblue/usr/share/backgrounds/bluefin/12-bluefin-day.jxl
  system_files/silverblue/usr/share/backgrounds/bluefin/12-bluefin-night.jxl
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
  system_files/silverblue/usr/share/gnome-background-properties/12-bluefin.xml
Labels: lgtm, size:XS

#1990 fix: remove sddm workaround
  build_files/base/07-base-image-changes.sh
  system_files/kinoite/usr/lib/systemd/system/usr-share-sddm-themes.mount
  system_files/kinoite/usr/lib/tmpfiles.d/usr-share-ssdm-themes.conf
Labels: lgtm, size:S

#1992 fix(ci): remove footguns.
  .github/changelogs.py
  .github/workflows/build-image-beta.yml
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/build-iso-latest.yml
  .github/workflows/generate-release.yml
  .github/workflows/reusable-build-iso.yml
Labels: github_actions, lgtm, size:M
