Repository ublue-os/bluefin, pull requests merged in 2024-06, with the labels that each got.

#1443 chore(ci): disable asus gts builds
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:XS

#1444 chore: sh uses =
  system_files/shared/usr/share/ublue-os/bluefin-cli/bling.sh
Labels: lgtm, size:XS

#1449 chore: make ujust bluefin-cli more robust
  just/bluefin-system.just
  system_files/shared/usr/libexec/ublue-bling.sh
Labels: lgtm, size:L

#1453 chore(ci): build stable ISOs
  .github/workflows/build-bluefin-stable-iso.yml
Labels: size:S

#1452 chore(ci): build stable tag weekly on tuesdays
  .github/workflows/build-coreos-aurora.yml
  .github/workflows/build-coreos-bluefin.yml
Labels: github_actions, lgtm, size:XS

#1433 chore(ci): clean up workflow names
  .github/workflows/build-39-aurora.yml
  .github/workflows/build-39-bluefin.yml
  .github/workflows/build-40-aurora.yml
  .github/workflows/build-40-bluefin.yml
  .github/workflows/build-aurora-iso.yml
  .github/workflows/build-bluefin-gts-iso.yml
  .github/workflows/build-bluefin-latest-iso.yml
  .github/workflows/build-coreos-aurora.yml
  .github/workflows/build-coreos-bluefin.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  .github/workflows/reusable-image-scan.yml
Labels: lgtm, size:S

#1458 fix: remove conflicting nvidia initramfs files
  build_files/shared/initramfs.sh
  system_files/shared/usr/lib/dracut/dracut.conf.d/95-nvidia.conf
  system_files/shared/usr/lib/modprobe.d/nvidia.conf
  system_files/shared/usr/lib/modprobe.d/nvk.conf
Labels: bug, size:S

#1459 fix: reorder nvidia install for coreos
  build_files/base/cleanup.sh
  build_files/base/install-akmods.sh
Labels: lgtm, size:M

#1461 chore(ci): Switch GTS/Stable to only Scheduled builds. Build ISOs weekly for GTS with schedule
  .github/workflows/build-39-aurora.yml
  .github/workflows/build-39-bluefin.yml
  .github/workflows/build-coreos-aurora.yml
  .github/workflows/build-coreos-bluefin.yml
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:M

#1462 fix(motd): clarify banner toggle wording
  system_files/kinoite/usr/share/ublue-os/motd/bluefin.md
  system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
Labels: documentation, lgtm, size:XS

#1466 feat: seasonal variation in sunrise/sunset times for seasonal Bluefin backgrounds
  system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-autumn-dynamic.xml
  system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-spring-dynamic.xml
  system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-summer-dynamic.xml
  system_files/silverblue/usr/share/backgrounds/bluefin/bluefin-winter-dynamic.xml
Labels: enhancement, lgtm, size:M
