Repository ublue-os/bluefin, pull requests merged in 2024-12, with the labels that each got.

#1997 fix: remove background-logo extension, restore gnome-tour
  packages.json
Labels: lgtm, size:XS

#1996 feat(packages): add google-noto-fonts-all
  packages.json
Labels: enhancement, lgtm, size:XS

#2007 feat: accent color theming for fastfetch and MOTD
  system_files/kinoite/etc/profile.d/aurora-fastfetch.sh
  system_files/kinoite/usr/share/fish/vendor_conf.d/aurora-fastfetch.fish
  system_files/shared/usr/libexec/ublue-bling-fastfetch
  system_files/shared/usr/libexec/ublue-motd
  system_files/shared/usr/share/ublue-os/motd/themes/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/yellow.json
  system_files/silverblue/etc/fish/conf.d/bluefin-fastfetch.fish
  system_files/silverblue/etc/profile.d/bluefin-fastfetch.sh
Labels: enhancement, lgtm, size:XL

#2008 fix(accent-color): light theme for accent colored motd
  system_files/shared/usr/libexec/ublue-motd
  system_files/shared/usr/share/ublue-os/motd/themes/dark/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/yellow.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/yellow.json
Labels: bug, lgtm, size:XL

#2006 fix: rename HWE ISOs in checksum files
  .github/workflows/reusable-build-iso.yml
Labels: iso, lgtm, size:XS

#2013 feat(packages): Add `ddcutil`
  packages.json
Labels: enhancement, lgtm, size:XS

#2018 fix(motd): remove light theme and make motd more monochrome
  system_files/kinoite/usr/share/ublue-os/motd/bluefin.md
  system_files/shared/usr/libexec/ublue-motd
  system_files/shared/usr/share/ublue-os/motd/themes/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/dark/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/light/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/yellow.json
  system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
Labels: lgtm, size:XL

#2019 fix(motd): use bold for color blocks instead of background color
  system_files/shared/usr/share/ublue-os/motd/themes/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/yellow.json
Labels: lgtm, size:S

#2024 docs: update readme
  README.md
Labels: size:S

#2023 chore: turn off aurora builds
  .github/workflows/build-image-beta.yml
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/build-iso-latest.yml
  .github/workflows/build-iso-stable.yml
Labels: github_actions, size:S

#2027 chore(aurora): remove all remaining aurora things from the system
  Justfile
  just/bluefin-system.just
  system_files/dx/usr/libexec/bluefin-dx-kvmfr-setup
  system_files/dx/usr/libexec/bluefin-incus
  system_files/shared/etc/profile.d/askpass.sh
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: size:M

#2032 docs: update description
  README.md
Labels: size:XS

#1993 fix: remove pkcs11-provider workaround
  build_files/base/18-workarounds.sh
Labels: lgtm, size:S

#2014 feat: allow non-official image repositories in ublue-rollback-helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: enhancement, lgtm, size:XS

#2016 fix: pass `repo_organization` to build script to ensure correct image metadata
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:S

#1998 feat(ujust): make setup-cockpit work more consistently and track container existence
  just/bluefin-apps.just
Labels: enhancement, lgtm, size:M

#2037 chore: Replace myself with tulizrockz for project sponsorship
  .github/FUNDING.yml
Labels: lgtm, size:XS

#2021 fix: unpin 6.11.3 kernel
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#2031 feat(iso): add File Roller by default
  bluefin_flatpaks/flatpaks
Labels: iso, lgtm, size:XS

#2040 fix: remove Alt-F5 from GNOME unmaximize keybinding
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: dx, lgtm, size:XS

#2029 chore(feat): adjust cron timers
  .github/workflows/build-image-beta.yml
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/generate-release.yml
Labels: github_actions, lgtm, size:S

#2033 fix: remove aurora from changelogs
  .github/changelogs.py
Labels: bug, lgtm, size:S

#2044 chore: remove more aurora mentions
  .github/workflows/build-iso-latest.yml
  .github/workflows/build-iso-stable.yml
  .github/workflows/clean.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  boot_menu.yml
Labels: github_actions, lgtm, size:M

#2045 fix(dx): disable kvmfr and podman-bootc repos on cleanup
  build_files/dx/09-cleanup-dx.sh
Labels: dx, lgtm, size:XS

#2052 chore: workaround podman image scp leaving behind temporary files in /var/tmp
  Justfile
Labels: bug, lgtm, size:XS

#2057 chore: remove kinoite plymouth image
  system_files/shared/usr/share/plymouth/themes/spinner/kinoite-watermark.png
Labels: lgtm, size:XS

#2061 Remove freeipa-client and sssd-ipa from Bluefin images
  packages.json
Labels: bug, lgtm, size:XS

#2064 feat: set dash-to-dock to apply built-in theme
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, lgtm, size:XS

#2068 ublue-os/bluefin fix: Update README.md with the correct project introduction link
  README.md
Labels: documentation, lgtm, size:XS

#2069 fix: Add skew fixes
  build_files/base/01-build-fix.sh
Labels: lgtm, size:M

#2047 fix: install bash-prexec with brew on cli bling
  build_files/base/05-override-install.sh
  system_files/shared/usr/share/ublue-os/bluefin-cli/bling.sh
  system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: brew, lgtm, size:XS

#2070 fix: remove wl akmod
  build_files/base/03-install-kernel-akmods.sh
Labels: bug, lgtm, size:XS

#2073 fix(ujust, benchmark): make benchmark be run on unique path on tmp
  just/bluefin-system.just
Labels: bug, lgtm, size:XS

#2074 feat(hwe-additions): Load pinctrl for more Surface devices
  build_files/base/09-hwe-additions.sh
Labels: enhancement, lgtm, size:XS

#2072 fix: return on bling.sh if it already got sourced
  system_files/shared/usr/share/ublue-os/bluefin-cli/bling.sh
Labels: bug, lgtm, size:XS
