Repository ublue-os/bluefin, pull requests merged in 2024-08, with the labels that each got.

#1561 chore(ci): fix gts kernel version check
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:XS

#1560 fix: clear flatpak's font cache
  system_files/shared/usr/libexec/ublue-user-setup
Labels: bug, lgtm, size:XS

#1532 fead: Add dialog boxes
  packages.json
Labels: enhancement, size:XS

#1553 feat: set gnome animation speed to .9
  system_files/silverblue/usr/etc/environment
Labels: enhancement, lgtm, size:XS

#1576 Added the initial kubernetes.Brewfile
  system_files/shared/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, lgtm, size:XS

#1573 fix(nvidia): pin Nvidia drivers to 555
  .github/workflows/reusable-build.yml
  Containerfile
Labels: bug, lgtm, size:XS

#1564 feat(bluefin-cli): add tealdeer as tldr
  system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: enhancement, lgtm, size:XS

#1578 fix: Disable pipewire camera handling temporarily
  system_files/shared/usr/share/wireplumber/wireplumber.conf.d/10-disable-camera.conf
Labels: bug, lgtm, size:XS

#1579 feat: add kwin rules for google chrome stable/unstable and flathub steam
  system_files/kinoite/usr/share/kde-settings/kde-profile/default/xdg/kwinrulesrc
Labels: enhancement, size:S

#1585 Revert "fix(nvidia): pin Nvidia drivers to 555"
  .github/workflows/reusable-build.yml
  Containerfile
Labels: github_actions, lgtm, size:XS

#1584 feat(bluefin-cli): add dysk
  system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: enhancement, lgtm, size:XS

#1569 feat: container indicator for fish shell
  system_files/shared/usr/share/fish/vendor_functions.d/fish_prompt.fish
Labels: enhancement, size:M

#1580 fix: Move files in /usr/etc to /etc
  build_files/aurora-changes.sh
  build_files/branding-dx.sh
  build_files/branding.sh
  build_files/build-base.sh
  build_files/fetch-install.sh
  build_files/fetch-quadlets.sh
  build_files/systemd.sh
  system_files/dx/etc/profile.d/vscode-bluefin-profile.sh
  system_files/dx/etc/skel/.config/Code/User/settings.json
  system_files/kinoite/etc/dconf/db/local.d/01-ptyxis
  system_files/kinoite/etc/profile.d/aurora-fastfetch.sh
  system_files/kinoite/etc/profile.d/ksshaskpass.sh
  system_files/kinoite/etc/skel/.config/gtk-4.0/gtk.css
  system_files/kinoite/etc/skel/.config/gtk-4.0/kde_window_geometry.css
  system_files/kinoite/etc/xdg/kcm-about-distrorc
  system_files/kinoite/etc/xdg/kdeglobals
  system_files/kinoite/etc/xdg/krunnerrc
  system_files/kinoite/etc/xdg/kwinrc
  system_files/shared/etc/distrobox/distrobox.conf
  system_files/shared/etc/distrobox/distrobox.example
  system_files/shared/etc/profile.d/askpass.sh
  system_files/shared/etc/profile.d/bluefin-firstboot.sh
  system_files/shared/etc/profile.d/brew-bash-completion.sh
  system_files/shared/etc/profile.d/neofetch.sh
  system_files/shared/etc/profile.d/open.sh
  system_files/shared/etc/security/limits.d/30-brew-limits.conf
  system_files/shared/etc/skel/.config/autostart/bluefin-firstboot.desktop
  system_files/shared/etc/skel/.config/toolbox/host-welcome-shown
  system_files/shared/etc/skel/.local/share/flatpak/overrides/com.google.Chrome
  system_files/shared/etc/skel/.local/share/flatpak/overrides/com.visualstudio.code
  system_files/shared/etc/skel/.local/share/org.gnome.Ptyxis/palettes/catppuccin-dynamic.palette
  system_files/shared/etc/skel/.var/app/io.github.dvlv.boxbuddyrs/config/glib-2.0/settings/keyfile
  system_files/shared/etc/systemd/user.conf
  system_files/shared/etc/ublue-update/ublue-update.toml
  system_files/shared/etc/yafti.yml
  system_files/shared/etc/zsh/zlogin
  system_files/shared/etc/zsh/zlogout
  system_files/shared/etc/zsh/zprofile
  system_files/shared/etc/zsh/zshenv
  system_files/shared/etc/zsh/zshrc
  system_files/shared/usr/lib/systemd/system/ublue-etc-merge.service
  system_files/shared/usr/lib/systemd/system/ublue-guest-user.service
  system_files/shared/usr/libexec/ublue-user-setup
  system_files/silverblue/etc/dconf/db/gdm.d/01-ublue
  system_files/silverblue/etc/dconf/db/local.d/01-ublue
  system_files/silverblue/etc/dconf/db/local.d/02-bluefin-folders
  system_files/silverblue/etc/dconf/db/local.d/locks/01-ublue-lock
  system_files/silverblue/etc/dconf/profile/gdm
  system_files/silverblue/etc/dconf/profile/user
  system_files/silverblue/etc/environment
  system_files/silverblue/etc/profile.d/bluefin-fastfetch.sh
Labels: bug, dx, size:M

#1589 chore(ci): prevent pinning build-container-installer action digest
  .github/renovate.json5
Labels: lgtm, size:XS

#1601 fix: Correct placement of ublue-update.toml until path changed
  build_files/fetch-install.sh
Labels: bug, lgtm, size:XS

#1602 docs: update public key filename
  README.md
Labels: documentation, lgtm, size:XS

#1588 feat: ollama ujust script, some additions for removal verbs for the ollama and open-webui containers.
  just/bluefin-tools.just
Labels: enhancement, size:M

#1599 feat(gnome): increase check-alive-timeout
  system_files/silverblue/etc/dconf/db/local.d/01-ublue
Labels: enhancement, lgtm, size:XS

#1605 fix: disable evdi
  build_files/install-akmods.sh
Labels: bug, lgtm, size:XS

#1586 fix(dx): adds a systemd unit workaround service to relabel libvirt files
  build_files/systemd-dx.sh
  system_files/dx/usr/lib/systemd/system/libvirt-workaround.service
  system_files/dx/usr/lib/tmpfiles.d/libvirt-workaround.conf
Labels: dx, lgtm, size:S

#1611 make `ujust ollama` show help
  just/bluefin-tools.just
Labels: bug, lgtm, size:XS

#1613 revert: "Added new dinosaur logos for fastfetch"
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/ducky.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/luke.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/runner.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/ducky
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/luke
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/runner
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/ducky
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/luke
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/runner
Labels: lgtm, size:L

#1621 fix: fix toggle-tailscale just command on aurora
  just/bluefin-system.just
Labels: lgtm, size:S

#1609 feat: add DNS resolution for libvirt guests
  packages.json
Labels: enhancement, size:XS

#1625 feat: disable ollama-web quadlet auth
  just/bluefin-tools.just
Labels: enhancement, lgtm, size:XS

#1631 feat: switch to autumn wallpapers
  system_files/silverblue/etc/dconf/db/local.d/01-ublue
Labels: enhancement, lgtm, size:XS

#1635 fix: remove xpadneo
  build_files/install-akmods.sh
Labels: lgtm, size:XS
