Repository ublue-os/bluefin, pull requests merged in 2024-10, with the labels that each got.

#1729 chore: added ctrl+alt+return keybind for host ptyxis
  system_files/silverblue/etc/dconf/db/local.d/01-ublue
Labels: enhancement, size:XS

#1728 docs: Added description to invokeai entry
  just/bluefin-tools.just
Labels: documentation, lgtm, size:XS

#1732 feat: add specific flatpaks to dx images
  .github/workflows/reusable-build-iso.yml
  dx_flatpaks/flatpaks
Labels: dx, lgtm, size:XS

#1733 feat(dx): add virt-v2v
  packages.json
Labels: dx, lgtm, size:XS

#1723 fix: remove scx-scheds
  packages.json
Labels: bug, lgtm, size:XS

#1658 fix: don't update if on a metered connection
  system_files/shared/etc/ublue-update/ublue-update.toml
Labels: bug, lgtm, size:XS

#1738 feat: add setools-console
  packages.json
Labels: enhancement, lgtm, size:XS

#1745 fix: Ollama WebUI isn't started by the ujust command
  just/bluefin-tools.just
Labels: bug, lgtm, size:XS

#1748 chore: update to handle the negativo17-only main image
  build_files/copr-repos-dx.sh
  build_files/install-akmods.sh
Labels: dx, lgtm, size:S

#1722 fix: switch latest images to use ungated upstream kernel
  .github/workflows/reusable-build.yml
  build_files/cache_kernel.sh
Labels: bug, github_actions, lgtm, size:XS

#1750 chore: attempt to fix rechunker complaint of multiple kernels
  .github/workflows/reusable-build.yml
  build_files/cache_kernel.sh
Labels: lgtm, size:XS

#1751 chore(ci): retry on ghcr push failures
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:S

#1752 chore(ci): always replace kernel packages
  .github/workflows/reusable-build.yml
  build_files/cache_kernel.sh
  build_files/install-akmods.sh
Labels: bug, lgtm, size:S

#1754 chore(ci): replace vanilla kernels not asus/surface
  build_files/cache_kernel.sh
Labels: bug, lgtm, size:S

#1753 chore(ci): only maximize space if building image
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:S

#1757 fix: fix os-release naming
  build_files/branding.sh
  build_files/image-info.sh
Labels: lgtm, size:XS

#1758 fix: Don't show version, Use only Pretty Name
  system_files/shared/usr/share/ublue-os/ublue-os.jsonc
Labels: lgtm, size:XS

#1761 docs: remove out-of-date line in readme
  README.md
Labels: documentation, lgtm, size:XS

#1762 chore: install git-credential-libsecret on non-dx
  packages.json
Labels: lgtm, size:XS

#1771 feat: add cryfs to bluefin
  packages.json
Labels: enhancement, lgtm, size:S

#1769 feat: add random dinos to fish fastfetch
  system_files/silverblue/usr/share/fish/vendor_conf.d/bluefin-fastfetch.fish
Labels: enhancement, lgtm, size:XS

#1773 chore(ci): always build latest images for both varieties
  .github/workflows/build-latest-aurora.yml
  .github/workflows/build-latest-bluefin.yml
Labels: github_actions, lgtm, size:XS

#1767 fix: just dx-group append group entry from /usr/lib/group
  just/bluefin-system.just
  system_files/dx/usr/libexec/bluefin-dx-groups
Labels: dx, lgtm, size:M

#1777 chore: update bug-report.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: lgtm, size:XS

#1779 feat: enable stable-daily channel
  .github/workflows/build-coreos-aurora.yml
  .github/workflows/build-coreos-bluefin.yml
  .github/workflows/reusable-build.yml
Labels: enhancement, github_actions, lgtm, size:S

#1780 feat: Add Borgbackup on the image for both Aurora and Bluefin
  packages.json
Labels: enhancement, lgtm, size:XS

#1784 chore: disable autostart behavior for solaar
  build_files/cleanup.sh
Labels: lgtm, size:XS

#1791 chore(docs): Separate Bluefin and Aurora documentation
  system_files/kinoite/usr/share/applications/documentation.desktop
  system_files/silverblue/usr/share/applications/documentation.desktop
Labels: documentation, lgtm, size:S

#1797 feat: ublue-rollback-helper - add stable-daily to targets
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: enhancement, lgtm, size:XS

#1799 fix: fix cryfs error on bluefin-gts
  packages.json
Labels: bug, lgtm, size:XS

#1803 feat(ci): Build stable weekly on the same day as gts
  .github/workflows/build-coreos-aurora.yml
  .github/workflows/build-coreos-bluefin.yml
Labels: github_actions, lgtm, size:XS

#1802 fix: don't attempt to pull zfs on beta
  .github/workflows/reusable-build.yml
  Containerfile
  build_files/install-akmods.sh
Labels: lgtm, size:S

#1807 fix: restore missing wallpapers in aurora
  build_files/aurora-changes.sh
  system_files/kinoite/usr/share/wallpapers/greg-rakozy-aurora/contents/images/5616x3744.jxl
  system_files/kinoite/usr/share/wallpapers/greg-rakozy-aurora/metadata.json
  system_files/kinoite/usr/share/wallpapers/jonatan-pie-aurora/contents/images/3944x2770.jxl
  system_files/kinoite/usr/share/wallpapers/jonatan-pie-aurora/metadata.json
  system_files/kinoite/usr/share/wallpapers/xe_clouds/contents/images/6000x4000.jxl
  system_files/kinoite/usr/share/wallpapers/xe_clouds/metadata.json
  system_files/kinoite/usr/share/wallpapers/xe_foothills/contents/images/4032x3024.jxl
  system_files/kinoite/usr/share/wallpapers/xe_foothills/metadata.json
  system_files/kinoite/usr/share/wallpapers/xe_space_needle/contents/images/6000x4000.jxl
  system_files/kinoite/usr/share/wallpapers/xe_space_needle/metadata.json
  system_files/kinoite/usr/share/wallpapers/xe_sunset/contents/images/6000x4000.jxl
  system_files/kinoite/usr/share/wallpapers/xe_sunset/metadata.json
  system_files/silverblue/usr/share/backgrounds/xe_clouds.jxl
  system_files/silverblue/usr/share/backgrounds/xe_foothills.jxl
  system_files/silverblue/usr/share/backgrounds/xe_space_needle.jxl
  system_files/silverblue/usr/share/backgrounds/xe_sunset.jxl
Labels: aurora, lgtm, size:M

#1808 chore: lighten fallback pcolor for wallpapers on bluefin
  system_files/silverblue/usr/share/gnome-background-properties/01-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/02-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/03-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/04-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/05-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/06-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/07-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/08-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/09-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/10-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/11-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/12-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/chicken.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_clouds.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_foothills.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_space_needle.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_sunset.xml
Labels: enhancement, lgtm, size:L

#1801 feat(ci): turn on F41 builds
  .github/workflows/build-beta-aurora.yml
  .github/workflows/build-beta-bluefin.yml
  .github/workflows/reusable-build.yml
  build_files/bluefin-changes.sh
  build_files/bootc.sh
  build_files/copr-repos.sh
  packages.json
Labels: github_actions, lgtm, size:L

#1810 feat: theming updates
  build_files/bluefin-changes.sh
  packages.json
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, size:S

#1819 feat: made Documentation, Community and System Update icons themeable
  system_files/kinoite/usr/share/applications/documentation.desktop
  system_files/shared/usr/share/applications/Discourse.desktop
  system_files/shared/usr/share/applications/system-update.desktop
  system_files/shared/usr/share/pixmaps/ublue-discourse.svg
  system_files/shared/usr/share/pixmaps/ublue-docs.svg
  system_files/shared/usr/share/pixmaps/ublue-update.svg
  system_files/silverblue/usr/share/applications/documentation.desktop
Labels: enhancement, lgtm, size:XS

#1820 feat: move fish fastfetch config for user customizability
  system_files/silverblue/etc/fish/conf.d/bluefin-fastfetch.fish
Labels: enhancement, lgtm, size:XS

#1828 fix(dx): cockpit-bridge replaces cockpit-pcp
  packages.json
Labels: dx, lgtm, size:XS

#1815 refactor(ci): stable-daily tagging
  .github/workflows/build-coreos-aurora-daily.yml
  .github/workflows/build-coreos-aurora-weekly.yml
  .github/workflows/build-coreos-bluefin-daily.yml
  .github/workflows/build-coreos-bluefin-weekly.yml
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:M

#1813 feat: apply theming updates & enable xwayland scaling
  build_files/bluefin-changes.sh
  packages.json
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, lgtm, size:M

#1831 feat: hide all windows (show desktop) via Super+D
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: enhancement, lgtm, size:XS

#1836 fix: limit the number of days in rollback-helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: bug, lgtm, size:XS

#1838 fix(just): change dx-group to a reboot message
  just/bluefin-system.just
Labels: dx, lgtm, size:XS

#1842 feat: add adw-gtk3-theme
  aurora_flatpaks/flatpaks
  bluefin_flatpaks/flatpaks
  packages.json
Labels: enhancement, lgtm, size:XS

#1846 fix: match bazzite's vrr/fractional scaling options
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: bug, lgtm, size:XS

#1848 revert: "fix: match bazzite's vrr/fractional scaling options"
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
Labels: lgtm, size:XS

#1847 fix: broken scale-monitor-framebuffer
  build_files/bluefin-changes.sh
Labels: bug, lgtm, size:XS

#1852 chore: fix GTS source fedora version
  .github/workflows/reusable-build.yml
Labels: github_actions, size:XS

#1853 chore: fix builds by enabling updates
  build_files/build-base.sh
  build_files/build-fix.sh
Labels: lgtm, size:S

#1854 chore(ci): Don't pull zfs on latest.
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:XS
