Repository ublue-os/bluefin, pull requests merged in 2025-04, with the labels that each got.

#2301 chore: unmark private "install-system-flatpaks" just recipie (#2299)
  just/bluefin-system.just
Labels: lgtm, size:XS, just

#2294 fix(brew): remove override config for brewfiles
  system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
  system_files/shared/usr/share/ublue-os/homebrew/kubernetes.Brewfile
Labels: brew, lgtm, size:S

#2305 chore: remove redundant ublue icons
  system_files/shared/usr/share/pixmaps/ublue-discourse.svg
  system_files/shared/usr/share/pixmaps/ublue-docs.svg
  system_files/shared/usr/share/pixmaps/ublue-update.svg
Labels: lgtm, size:XS

#2307 chore: Remove patch for GTS bluefin backgrounds
  build_files/base/05-override-install.sh
Labels: lgtm, size:S

#2281 chore: simplify packages.sh install scripts
  build_files/base/04-packages.sh
  build_files/dx/03-packages-dx.sh
  just/bluefin-apps.just
  packages.json
Labels: dx, lgtm, size:L

#2314 chore(ci): test for buildjet
  .github/workflows/reusable-build.yml
Labels: github_actions, size:XS

#2315 chore: try buildjet 22.04
  .github/workflows/reusable-build.yml
Labels: size:XS

#2317 chore(fix): finish buildjet/blacksmith test
  .github/workflows/reusable-build.yml
Labels: github_actions, size:XS

#2319 chore(fix): use ubuntu 24.04
  .github/workflows/reusable-build.yml
Labels: size:XS

#2320 feat(cli): Add install-gaming-flatpaks ujust command
  just/bluefin-apps.just
Labels: lgtm, size:S, just

#2321 Add samsung unified linux driver
  packages.json
Labels: enhancement, lgtm, size:XS

#2326 chore: add more CODEOWNERS for this repo
  .github/CODEOWNERS
Labels: size:XS

#2328 chore: beta should build even if rpmfusion isn't working
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:S

#2136 chore: switch from ublue-update to uupd as default automatic updater
  build_files/base/05-override-install.sh
  build_files/base/17-cleanup.sh
  packages.json
  system_files/shared/etc/ublue-update/ublue-update.toml
  system_files/shared/usr/share/ublue-os/just/10-update.just
  system_files/shared/usr/share/ublue-os/topgrade-bootc.toml
  system_files/shared/usr/share/ublue-os/topgrade.toml
Labels: lgtm, size:M

#2312 feat: add refine
  bluefin_flatpaks/flatpaks
Labels: enhancement, lgtm, size:XS

#2329 feat(packaged): switch from fedora media writer to impression
  bluefin_flatpaks/flatpaks
Labels: enhancement, lgtm, size:XS

#2332 feat: add WIP live ISO workflow
  .github/workflows/build-iso-test.yml
  iso_files/configure_iso.sh
Labels: iso, size:L

#2333 chore(iso): use a matrix for fedora versions
  .github/workflows/build-iso-test.yml
Labels: size:S

#2336 feat(liveiso): add flatpaks, fix readymade install, correct image tag
  .github/workflows/build-iso-test.yml
  iso_files/configure_iso.sh
  iso_files/system-flatpaks.txt
Labels: iso, size:M

#2338 chore(liveiso): add config file
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:S

#2339 feat: install v4l2loopback from terra
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/05-override-install.sh
Labels: enhancement, lgtm, size:S

#2311 fix(packages): remove stress-ng
  packages.json
Labels: size:XS

#2310 fix(packages): remove simple-scan
  packages.json
Labels: size:XS

#2309 fix(packages): remove topgrade
  packages.json
Labels: size:XS

#2169 chore: use solaar flatpak instead of the system package
  bluefin_flatpaks/flatpaks
  build_files/base/17-cleanup.sh
  packages.json
Labels: size:XS

#2155 feat: remove inputleap from base image
  packages.json
Labels: enhancement, size:XS

#2342 fix(dx): remove devpod from the image
  packages.json
Labels: dx, lgtm, size:XS

#2345 feat(cli): replace ProtonUp-Qt with ProtonPlus
  just/bluefin-apps.just
Labels: enhancement, lgtm, size:XS, just

#2346 fix(dx): install docker-ce from test repos in F42
  build_files/dx/04-override-install-dx.sh
  packages.json
  system_files/dx/etc/yum.repos.d/docker-ce.repo
Labels: dx, lgtm, size:S

#2343 feat(dx): add devtoolbox and devpod
  dx_flatpaks/flatpaks
Labels: dx, lgtm, size:XS

#2352 feat(iso): enable workflow for `:stable` and `:beta` + make config adapt to it
  .github/workflows/build-iso-live.yml
  iso_files/configure_iso.sh
Labels: iso, size:S

#2353 fix(live,iso): correctly get image tags and flavor for readymade config
  .github/workflows/build-iso-live.yml
  iso_files/configure_iso.sh
Labels: iso, size:S

#2357 fix: correct name for devpod flatpak
  dx_flatpaks/flatpaks
Labels: bug, lgtm, size:XS

#2359 feat(live-iso): enable GTS builds for live ISOs
  .github/workflows/build-iso-live.yml
Labels: iso, lgtm, size:XS

#2355 fix(nvidia-open): correctly identify nvidia-open on image-info.json + fix live ISO nvidia
  build_files/base/00-image-info.sh
  iso_files/configure_iso.sh
Labels: iso, size:XS

#2360 Revert "feat: remove v4l2loopback and rpmfusion for Fedora 42+ (#2330)"
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:S

#2362 chore: install Docker CE from stable repos
  build_files/dx/04-override-install-dx.sh
  packages.json
Labels: dx, lgtm, size:S

#2368 fix: remove xpadneo
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#2370 chore: remove beta builds
  .github/workflows/build-image-beta.yml
  .github/workflows/build-iso-live.yml
Labels: github_actions, lgtm, size:S

#2369 chore(liveiso): install Readymade from nightly
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:XS

#2367 fix: Enable iptable_nat for docker-in-docker
  build_files/shared/build-dx.sh
Labels: bug, lgtm, size:XS

#2372 revert: "chore(liveiso): install Readymade from nightly"
  iso_files/configure_iso.sh
Labels: size:XS

#2373 fix(live): make it so nvidia-open ISOs have proper naming
  .github/workflows/build-iso-live.yml
Labels: iso, size:S

#2374 fix(nvidia,live-iso): ensure kargs are being passed to nvidia ISOs
  .github/workflows/build-iso-live.yml
Labels: size:XS

#2375 chore: remove old flatpak list
  bluefin_flatpaks/flatpaks
Labels: size:M

#2376 chore: remove old ISO files
  .github/workflows/build-iso-gts.yml
  .github/workflows/build-iso-latest.yml
  .github/workflows/build-iso-stable.yml
  .github/workflows/build-isos.yml
Labels: iso, size:M

#2377 chore: cleanup reusable build ISO
  .github/workflows/reusable-build-iso.yml
Labels: size:L

#2381 feat(live-iso): enable -latest for testing
  .github/workflows/build-iso-live.yml
Labels: iso, lgtm, size:XS

#2380 fix(just): adjust flatpak install location
  just/bluefin-system.just
Labels: lgtm, size:XS, just

#2382 fix(live-iso): disable more useless services for the ISO + ensure signing is enabled
  iso_files/configure_iso.sh
Labels: size:S

#2379 chore(F42): Use patched gnome on f42
  build_files/base/05-override-install.sh
Labels: lgtm, size:S

#2378 fix(hwe): switch to skip-unavailable
  build_files/base/09-hwe-additions.sh
Labels: lgtm, size:XS, upstream

#2383 revert "chore: remove old flatpak list"
  bluefin_flatpaks/flatpaks
Labels: size:M

#2384 fix(live-iso): nvidia kargs + readymade on autostart
  iso_files/configure_iso.sh
Labels: iso, size:XS

#2385 fix(live-iso): make sure ublue-logo is on logomenu and bluefin package is up-to-date
  iso_files/configure_iso.sh
Labels: iso, size:XS

#2386 fix: reinstall bluefin-schemas on the live ISO
  iso_files/configure_iso.sh
Labels: iso, size:S

#2389 fix(live-iso): dont run any anaconda setup stages
  iso_files/configure_iso.sh
Labels: iso, size:M

#2390 fix: make readymade show up on the dock on newer builds
  iso_files/configure_iso.sh
Labels: size:XS

#2391 feat(flatpaks): add pinta and thunderbird
  iso_files/system-flatpaks.txt
Labels: enhancement, lgtm, size:XS

#2395 feat: add mokutil secureboot key enrollment script
  iso_files/configure_iso.sh
Labels: enhancement, iso, lgtm, size:S

#2398 chore(iso): switch back to readymade nightly
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:XS

#2388 chore(live-iso): hide custom partitioning button
  iso_files/configure_iso.sh
Labels: iso, size:XS

#2400 chore(iso): build nightly
  .github/workflows/build-iso-live.yml
Labels: iso, size:XS

#2399 fix(incus): re-enable ganto copr for incus
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/09-cleanup-dx.sh
Labels: bug, lgtm, size:XS

#2401 revert: "fix(incus): re-enable ganto copr for incus"
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/09-cleanup-dx.sh
Labels: size:XS

#2402 feat(iso): add docs and discourse to live session dock
  iso_files/configure_iso.sh
Labels: iso, size:XS

#2406 chore(ci): enable stable-daily ISOs
  .github/workflows/build-iso-live.yml
Labels: size:XS

#2412 feat(motd): update motd
  system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
Labels: size:XS

#2411 fix(motd): turn tips back on
  system_files/shared/usr/share/ublue-os/motd/template.md
Labels: bug, size:XS

#2289 fix(flatpak): Remove Fedora Flatpak remote
  Justfile
  build_files/base/17-cleanup.sh
Labels: lgtm, size:S, just

#2414 feat: include ISO flatpak list into the image
  .github/workflows/build-iso-live.yml
  Containerfile
  build_files/shared/build-base.sh
  iso_files/system-flatpaks-dx.list
  iso_files/system-flatpaks.list
  just/bluefin-system.just
Labels: enhancement, iso, lgtm, size:M, just

#2418 fix(ublue-rollback-helper): add rebase guards to rebase helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: bug, lgtm, size:XS

#2420 chore: cleanup everything brew-related that ublue-brew entirely covers
  build_files/base/10-brew.sh
  build_files/shared/build-base.sh
  system_files/shared/usr/lib/systemd/system-preset/02-homebrew-update.preset
  system_files/shared/usr/lib/systemd/system/brew-update.service
  system_files/shared/usr/lib/systemd/system/brew-update.timer
  system_files/shared/usr/lib/systemd/system/brew-upgrade.service
  system_files/shared/usr/lib/systemd/system/brew-upgrade.timer
Labels: brew, lgtm, size:M

#2421 fix: make it so the ISO text files arent broken for older updates
  iso_files/README.md
  iso_files/system-flatpaks.txt
Labels: iso, lgtm, size:M

#2428 fix(live-iso): allow for offline installation
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:XS

#2422 fix: readd gnome-tweaks
  packages.json
Labels: size:XS

#2426 chore: use main repo for nvidia-install.sh
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#2429 fix(live-iso): functioning bentos config
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:S

#2431 Update configure_iso.sh
  iso_files/configure_iso.sh
Labels: size:XS

#2432 feat: add bluefin offline documentation to `/usr/share/doc`
  build_files/base/05-override-install.sh
Labels: documentation, lgtm, size:XS

#2435 Update bug-report.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: size:XS

#2438 fix: add temporary workaround service for missing `/etc/hostname` file
  build_files/base/17-cleanup.sh
  system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
Labels: bug, lgtm, size:S

#2440 fix: /etc/hostname fixup
  system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
Labels: bug, lgtm, size:XS

#2441 chore: pin GTS and Stable to kernel 6.13.8
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
Labels: lgtm, size:XS, pin

#2433 feat(ci): switch to renovate from cronjobs
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-image-stable.yml
  image-versions.yml
Labels: github_actions, lgtm, size:M

#2442 chore(renovate): configure auto merging for Renovate digest updates
  .github/renovate.json5
Labels: lgtm, size:XS

#2444 feat(iso): add gparted
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:XS
