Repository ublue-os/bluefin, pull requests merged in 2025-07, with the labels that each got.

#2729 docs: update tips
  system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
Labels: documentation, lgtm, size:XS

#2731 feat: add turbowarp to "education" section in bazaar
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#2730 fix(syntax): packages.json
  packages.json
Labels: lgtm, size:XS

#2739 chore(ci): remove old anaconda ISO workflows
  .github/workflows/build-iso-gts.yml
  .github/workflows/build-iso-stable.yml
Labels: github_actions, lgtm, size:S

#2747 fix(bazaar): add NVIDIA workaround
  build_files/base/18-workarounds.sh
Labels: bug, lgtm, size:XS

#2743 feat(bazaar): add ytmdesktop
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, size:XS

#2742 chore: alphabetize flatpak lists
  bluefin_flatpaks/flatpaks
  dx_flatpaks/flatpaks
Labels: lgtm, size:S

#2741 fix(bazaar): blocklist com.google.ChromeDev
  system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
Labels: lgtm, size:XS

#2753 feat(bazaar): add easyeffects and jamesdsp
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#2764 feat(bazaar): add digger
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#2770 docs: update deepwiki link
  README.md
Labels: size:XS

#2777 chore: pin stable to kernel 6.14.11
  .github/workflows/build-image-stable.yml
Labels: lgtm, size:XS, pin

#2774 feat(bazaar): add Constrict
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#2794 fix(pin): downgrade libdex to 0.9.1
  build_files/base/18-workarounds.sh
Labels: lgtm, size:XS, pin

#2808 fix(build): use GITHUB_TOKEN for curl when needed
  .github/workflows/reusable-build.yml
  Containerfile
  Justfile
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/05-override-install.sh
  build_files/dx/04-override-install-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/build-dx.sh
  build_files/shared/utils/ghcurl
Labels: github_actions, lgtm, size:M

#2809 chore: try increasing compression on maximize build space
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:XS

#2847 docs: update links on README
  README.md
Labels: documentation, lgtm, size:XS

#2851 docs: updated readme
  README.md
Labels: size:M

#2804 feat: add git-svn
  packages.json
Labels: enhancement, lgtm, size:XS

#2857 chore: remove image dropdown
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: lgtm, size:S

#2839 feat(bazaar): add battle of wesnoth
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#2833 feat: add davfs2 to support Taildrive
  packages.json
Labels: enhancement, lgtm, size:XS

#2772 feat(bazaar): add elastic to dev section
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#2884 chore(ci): delete .github/workflows/notify-docs-release.yml
  .github/workflows/notify-docs-release.yml
Labels: github_actions, size:M
