Repository ublue-os/bluefin, pull requests merged in 2025-08, with the labels that each got.

#2879 fix: delete old changelog
  CHANGELOG.md
Labels: lgtm, size:XS

#2893 feat: add Waypipe
  packages.json
Labels: enhancement, lgtm, size:XS

#2921 fix(ci): use rootful container storage
  .github/workflows/reusable-build.yml
  Justfile
Labels: github_actions, lgtm, size:S

#2904 feat: centralized flatpaks list
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/reusable-build-iso-anaconda.yml
  .github/workflows/reusable-build-iso-readymade.yml
  Containerfile
  Justfile
  build_files/shared/build-base.sh
  flatpaks/system-flatpaks-dx.list
  flatpaks/system-flatpaks.list
  iso_files/system-flatpaks-dx.list
  iso_files/system-flatpaks.list
Labels: github_actions, lgtm, size:M, just

#2959 feat: add optional cloudflare upload to Anaconda Live ISO workflow
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, size:S

#2968 chore: enable progress on rclone for ISO Cloudflare uploads
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, lgtm, size:XS

#2983 revert: temporary change due to perms issue with image-info
  iso_files/configure_lts_iso_anaconda.sh
Labels: iso, size:XS

#2999 chore(template): update issue template
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation, lgtm, size:XS

#2978 docs: new stats for readme
  README.md
Labels: documentation, lgtm, size:S

#3006 fix: add bluefin AI tools ujust
  just/bluefin-apps.just
Labels: lgtm, size:XS, just

#3005 fix: remove ramalama from image
  packages.json
Labels: brew, lgtm, size:XS

#3063 chore(ci): set prerelease to false in release workflow
  .github/workflows/generate-release.yml
Labels: github_actions, lgtm, size:XS

#3073 feat(bazaar): give each picture a unique gradient
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:M

#3084 fix: use distroshelf and not boxbuddy
  flatpaks/system-flatpaks.list
Labels: bug, size:XS

#3086 feat(bazaar): add io.github.swordpuffin.rewaita to config.yaml
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#3113 chore: update Gnome package reference in changelogs.py
  .github/changelogs.py
Labels: dependencies, lgtm, size:XS
