Repository ublue-os/bluefin, pull requests merged in 2025-09, with the labels that each got.

#3133 chore: unpin gts and stable kernel
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
Labels: lgtm, size:XS, pin

#2972 fix: update logic for applying framework laptop 13 fixes
  system_files/shared/usr/share/ublue-os/system-setup.hooks.d/10-framework.sh
Labels: framework, lgtm, size:M

#3142 fix: remove a bunch of old workarounds
  build_files/base/18-workarounds.sh
Labels: lgtm, size:S

#3149 Update workflow triggers for latest images
  .github/workflows/build-image-latest-hwe.yml
Labels: github_actions, lgtm, size:S

#3154 feat: replace Sudoku entry with new package
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#3171 Update maintainer guidelines in copilot instructions
  .github/copilot-instructions.md
Labels: size:XS

#3200 Add 'bluefin-gdx' to cleanup packages list
  .github/workflows/clean.yml
Labels: size:XS

#3201 chore(iso): remove concurrency
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, size:XS

#3215 fix: remove ujust recipes referencing removed Brewfiles
  just/bluefin-apps.just
Labels: lgtm, size:S, just

#3210 feat(dx): add new clapgrep and concessio
  flatpaks/system-flatpaks-dx.list
Labels: dx, lgtm, size:XS

#3283 Add sshPilot to Bazaar development section
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: lgtm, size:XS

#3295 chore(dx): Add git-subtree
  packages.json
Labels: dx, lgtm, size:XS
