Repository ublue-os/bluefin, pull requests merged in 2025-02, with the labels that each got.

#2143 chore: un-cliwrap and use dnf5 instead of rpm-ostree (again)
  Containerfile
  build_files/base/01-build-fix.sh
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/09-hwe-additions.sh
  build_files/base/17-cleanup.sh
  build_files/base/19-initramfs.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/09-cleanup-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/clean-stage.sh
Labels: dx, lgtm, size:L

#2170 feat: update GTS kernel pin to 6.12.9
  .github/workflows/build-image-gts.yml
  Justfile
Labels: enhancement, lgtm, size:S

#2175 feat: add font manager and embellish to flatpak list
  bluefin_flatpaks/flatpaks
  dx_flatpaks/flatpaks
Labels: enhancement, lgtm, size:XS

#2179 fix: update topgrade.toml
  build_files/base/05-override-install.sh
  packages.json
  system_files/shared/usr/share/ublue-os/topgrade.toml
Labels: lgtm, size:XS

#2182 fix: make ujust update use direct calls to rpm-ostree and others
  system_files/shared/usr/share/ublue-os/just/10-update.just
Labels: bug, lgtm, size:XS

#2181 fix: remove ublue-update and rely on units to get auto updates instead
  build_files/base/05-override-install.sh
  build_files/base/17-cleanup.sh
  build_files/shared/build-base.sh
  packages.json
  system_files/shared/usr/share/ublue-os/just/10-update.just
Labels: lgtm, size:S

#2184 fix: remove bootc key from topgrade
  system_files/shared/usr/share/ublue-os/topgrade.toml
Labels: bug, lgtm, size:XS

#2185 chore(ci): support combined akmods-kernel-cache in build
  Justfile
  build_files/base/03-install-kernel-akmods.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
Labels: dx, lgtm, size:M

#2187 chore: add guards to ujust update
  system_files/shared/usr/share/ublue-os/just/10-update.just
Labels: lgtm, size:S

#2191 chore: disable vscode automated updates
  system_files/dx/etc/skel/.config/Code/User/settings.json
Labels: dx, lgtm, size:XS

#2192 feat(dx): add ramalama
  packages.json
Labels: dx, lgtm, size:XS

#2174 feat: add opentablet just recipe
  just/bluefin-apps.just
Labels: enhancement, lgtm, size:M

#2189 feat(just): add bluefin-specific changelogs
  system_files/shared/usr/share/ublue-os/just/10-update.just
Labels: enhancement, lgtm, size:XS

#2204 feat: Fix geolocation (Primarily for timezone detection) now that Mozilla has exited
  system_files/shared/etc/geoclue/conf.d/99-beacondb.conf
Labels: enhancement, lgtm, size:XS

#2198 feat: Add Nerd-Font Symbols to VSCode Editor Config #2196
  system_files/dx/etc/skel/.config/Code/User/settings.json
Labels: enhancement, lgtm, size:XS

#2207 revert: "feat: Fix geolocation (Primarily for timezone detection) now that Mozilla has exited"
  system_files/shared/etc/geoclue/conf.d/99-beacondb.conf
Labels: lgtm, size:XS

#2210 fix: remove old triple buffering patch
  build_files/base/05-override-install.sh
Labels: lgtm, size:XS

#2213 feat: add python3-pygit2
  packages.json
Labels: enhancement, lgtm, size:XS

#2214 fix: swap to mozc for japanese support
  packages.json
Labels: lgtm, size:XS

#2215 chore: remove alternatives workaround
  build_files/base/18-workarounds.sh
  build_files/shared/build-base.sh
  build_files/shared/build-dx.sh
Labels: lgtm, size:S

#2226 chore: pin latest to last 6.12 kernel
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-images.yml
Labels: github_actions, lgtm, size:M
