Repository ublue-os/bluefin, pull requests merged in 2025-03, with the labels that each got.

#2230 fix(ci): unpin 6.12 kernel in latest
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
Labels: github_actions, lgtm, size:XS

#2231 chore: Update README Badges
  README.md
Labels: documentation, size:XS

#2228 feat: add justfile recipe to retag broken NVIDIA ghcr images
  Justfile
Labels: enhancement, lgtm, size:S

#2239 feat: enable sbom generation
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:M

#2237 chore: remove deprecated SBOM workflow
  .github/syft.yml
  .github/workflows/reusable-build.yml
  .github/workflows/reusable-image-scan.yml
Labels: github_actions, size:L

#2240 fix: reference digest from retry action correctly
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:XS

#2241 fix: remove SBOMs temporarily
  .github/workflows/reusable-build.yml
Labels: github_actions, lgtm, size:M

#2243 fix: remove march wallpaper from GTS (f40)
  build_files/base/05-override-install.sh
  packages.json
Labels: lgtm, size:S

#2256 chorse: update config.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: size:XS

#2270 chore: unpin nvidia-install.sh script
  build_files/base/03-install-kernel-akmods.sh
  build_files/shared/build-base.sh
Labels: lgtm, size:XS

#2276 fix: revert dnf5 downgrade
  build_files/shared/build-base.sh
Labels: bug, lgtm, size:XS

#2278 chore: get beta building....
  Containerfile
  Justfile
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/17-cleanup.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/09-cleanup-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/build-dx.sh
  packages.json
Labels: lgtm, size:L, just

#2282 chore: update rechunk version
  Justfile
Labels: lgtm, size:XS, just

#2284 fix: update FUNDING.yml
  .github/FUNDING.yml
Labels: size:XS

#2285 fix: Remove nonAscii file name for iso building
  Justfile
  build_files/base/18-workarounds.sh
Labels: iso, lgtm, size:S, just

#2199 fix: only run ublue user services for human users
  system_files/dx/usr/lib/systemd/user/bluefin-dx-user-vscode.service
  system_files/shared/usr/lib/systemd/user/ublue-flatpak-manager.service
  system_files/shared/usr/lib/systemd/user/ublue-user-setup.service
Labels: dx, lgtm, size:XS

#2150 feat: Update VFIO to be bootc compliant
  build_files/dx/04-override-install-dx.sh
  just/bluefin-system.just
  system_files/dx/usr/lib/dracut/dracut.conf.d/80-vfio.conf
  system_files/dx/usr/libexec/bluefin-dx-kvmfr-setup
Labels: dx, lgtm, size:M

#2293 feat: enable terra and use switcheroo from there
  build_files/base/02-install-copr-repos.sh
  build_files/base/05-override-install.sh
Labels: enhancement, lgtm, size:M
