Repository ublue-os/bluefin, pull requests merged in 2025-06, with the labels that each got.

#2605 revert: "fix: pin mutter to .48.1-1 in F42"
  build_files/base/18-workarounds.sh
Labels: lgtm, size:XS, pin

#2608 fix: remove nautilus-open-any-terminal
  packages.json
Labels: bug, lgtm, size:XS

#2625 feat: add bazaar configs
  system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
  system_files/shared/usr/share/ublue-os/bazaar/gaming.png
  system_files/shared/usr/share/ublue-os/bazaar/music.png
  system_files/shared/usr/share/ublue-os/bazaar/office.png
  system_files/shared/usr/share/ublue-os/bazaar/streaming.png
  system_files/shared/usr/share/ublue-os/bazaar/utilities.png
Labels: lgtm, size:L

#2629 feat: add more cli text editor to blocklist and add Bluefin Recomends and Developer Tools for Bazaar
  system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:M, appstore

#2630 Replaced Bazaar Bazzite Images With Bluefin Images
  system_files/shared/usr/share/ublue-os/bazaar/gaming.png
  system_files/shared/usr/share/ublue-os/bazaar/music.png
  system_files/shared/usr/share/ublue-os/bazaar/office.png
  system_files/shared/usr/share/ublue-os/bazaar/streaming.png
  system_files/shared/usr/share/ublue-os/bazaar/utilities.png
Labels: lgtm, size:XS

#2635 feat: add more sections and apps
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, size:M, appstore

#2636 feat: add more sections and apps
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, size:M, appstore

#2640 feat: add more apps to the appstore
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, size:S

#2653 feat: add more apps and reorg
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, size:M

#2530 feat: Add fedora version to the rebase helper
  system_files/shared/usr/bin/ublue-rollback-helper
Labels: enhancement, lgtm, size:XS

#2670 fix: kick off build off of silverblue-main
  image-versions.yml
Labels: lgtm, size:XS

#2674 fix(bazaar): remove text background
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: lgtm, size:XS

#2675 feat(bazaar): add more applications
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:S

#2676 fix(bazaar): update firefox entry
  bluefin_flatpaks/flatpaks
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: bug, lgtm, size:XS

#2686 fix(bazaar): use proper filenames
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: bug, lgtm, size:S

#2687 fix(bazaar): final bazaar artwork fixes
  system_files/shared/usr/share/ublue-os/bazaar/06-bluefin.png
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: lgtm, size:M

#2691 feat(bazaar): darken background images and improve padding
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:XS

#2692 fix(bazaar): shorter descriptions
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: lgtm, size:M

#2693 fix: update config.yaml
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: size:XS

#2694 feat(bazaar): add more apps
  system_files/shared/usr/share/ublue-os/bazaar/config.yaml
Labels: enhancement, lgtm, size:S

#2695 docs: add deepwiki button
  README.md
Labels: size:XS

#2690 feat: remove gnome-software
  packages.json
Labels: enhancement, size:XS

#2710 docs: update badges
  README.md
Labels: size:XS

#2714 fix(motd): update 10-tips.md
  system_files/shared/usr/share/ublue-os/motd/template.md
  system_files/shared/usr/share/ublue-os/motd/tips/10-tips.md
Labels: lgtm, size:XS

#2719 fix: blocklist ptyxis flatpak
  system_files/shared/usr/share/ublue-os/bazaar/blocklist.txt
Labels: bug, lgtm, size:XS
