Repository ublue-os/bluefin, pull requests merged in 2025-05, with the labels that each got.

#2449 fix(just): add current user to dx-groups instead of root
  just/bluefin-system.just
Labels: lgtm, size:XS, just

#2451 fix(live-iso): add branding and fix config file ids
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:S

#2454 fix: make sure bluefin readymade configs dont conflict w/ readymade package
  iso_files/configure_iso.sh
Labels: bug, size:XS

#2455 fix(live-iso): ensure packages copr is enabled on the live ISO
  iso_files/configure_iso.sh
Labels: size:XS

#2457 fix(iso): fix link to forums
  iso_files/configure_iso.sh
Labels: iso, lgtm, size:XS

#2459 feat(live-iso): add live ISO workflow for LTS too
  .github/workflows/build-iso-live.yml
  iso_files/configure_iso.sh
Labels: iso, size:S

#2460 fix(live-iso): handling for LTS readymade installation
  iso_files/configure_iso.sh
Labels: size:XS

#2463 feat: use ublue-setup-services for setup services
  build_files/base/17-cleanup.sh
  build_files/dx/09-cleanup-dx.sh
  packages.json
  system_files/dx/etc/profile.d/vscode-bluefin-profile.sh
  system_files/dx/usr/lib/systemd/user/bluefin-dx-user-vscode.service
  system_files/dx/usr/libexec/bluefin-dx-user-vscode
  system_files/dx/usr/share/ublue-os/user-setup.hooks.d/10-vscode.sh
  system_files/shared/etc/profile.d/sb-key-notify-autostart.sh
  system_files/shared/etc/skel/.config/autostart/sb-key-notify.desktop
  system_files/shared/etc/ublue-os/setup.json
  system_files/shared/usr/bin/sb-key-notify
  system_files/shared/usr/lib/systemd/system/check-sb-key.service
  system_files/shared/usr/lib/systemd/system/ublue-system-setup.service
  system_files/shared/usr/lib/systemd/user/ublue-flatpak-manager.service
  system_files/shared/usr/lib/systemd/user/ublue-user-setup.service
  system_files/shared/usr/libexec/check-sb-key.sh
  system_files/shared/usr/libexec/ublue-flatpak-manager
  system_files/shared/usr/libexec/ublue-privileged-user-setup
  system_files/shared/usr/libexec/ublue-system-setup
  system_files/shared/usr/libexec/ublue-user-setup
  system_files/shared/usr/share/ublue-os/privileged-setup.hooks.d/10-tailscale.sh
  system_files/shared/usr/share/ublue-os/privileged-setup.hooks.d/99-flatpaks.sh
  system_files/shared/usr/share/ublue-os/system-setup.hooks.d/10-framework.sh
  system_files/shared/usr/share/ublue-os/user-setup.hooks.d/10-theming.sh
  system_files/shared/usr/share/ublue-os/user-setup.hooks.d/99-privileged.sh
Labels: enhancement, lgtm, size:L

#2465 chore: remove F40 references from build scripts - Fixes #2335
  Containerfile
  build_files/base/05-override-install.sh
  build_files/base/16-bootc.sh
  build_files/shared/build-base.sh
  packages.json
Labels: lgtm, size:M

#2466 chore: remove fedora-chromium-config* and fedora-bookmarks package
  packages.json
Labels: lgtm, size:S

#2430 chore: add a few upstream bootc configuration files for nvidia and `bootc install`
  build_files/base/03-install-kernel-akmods.sh
  system_files/shared/usr/lib/bootc/install/20-bluefin.toml
Labels: lgtm, size:XS, upstream

#2469 feat: use readymade from staging for fedora and centos
  iso_files/configure_iso.sh
Labels: enhancement, size:S

#2470 chore: fix install of ZFS after update to 2.3.2.
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS

#2468 feat: remove `silverblue` section on build_scripts + use bluefin and ublue packages for cleanup
  build_files/base/05-override-install.sh
  build_files/base/07-base-image-changes.sh
  build_files/shared/build-base.sh
  packages.json
  system_files/shared/etc/environment
  system_files/shared/usr/bin/xdg-terminal-exec
  system_files/shared/usr/lib/modprobe.d/amd-legacy.conf
  system_files/shared/usr/share/backgrounds/xe_clouds.jxl
  system_files/shared/usr/share/backgrounds/xe_foothills.jxl
  system_files/shared/usr/share/backgrounds/xe_space_needle.jxl
  system_files/shared/usr/share/backgrounds/xe_sunset.jxl
  system_files/shared/usr/share/plymouth/themes/spinner/silverblue-watermark.png
  system_files/shared/usr/share/polkit-1/actions/org.ublue.privileged.user.setup.policy
  system_files/shared/usr/share/polkit-1/rules.d/20-privileged-ruser.rules
  system_files/shared/usr/share/polkit-1/rules.d/99-pcscd.rules
  system_files/shared/usr/share/wallpapers/xe_clouds.jpeg
  system_files/shared/usr/share/wallpapers/xe_foothills.jpeg
  system_files/shared/usr/share/wallpapers/xe_space_needle.jpeg
  system_files/shared/usr/share/wallpapers/xe_sunset.jpeg
  system_files/shared/usr/share/wireplumber/wireplumber.conf.d/10-disable-camera.conf
  system_files/silverblue/usr/share/glib-2.0/schemas/zz0-bluefin-modifications.gschema.override
  system_files/silverblue/usr/share/gnome-background-properties/01-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/02-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/03-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/04-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/05-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/06-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/07-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/08-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/09-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/10-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/11-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/12-bluefin.xml
  system_files/silverblue/usr/share/gnome-background-properties/chicken.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_clouds.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_foothills.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_space_needle.xml
  system_files/silverblue/usr/share/gnome-background-properties/xe_sunset.xml
  system_files/silverblue/usr/share/ublue-os/motd/20-bluefin.md
Labels: enhancement, lgtm, size:L

#2474 chore: remove stable-daily and latest from ISOs
  .github/workflows/build-iso-live.yml
Labels: size:XS

#2475 fix(just): use system gsettings to configure terminal transparency
  just/bluefin-system.just
Labels: lgtm, size:XS, just

#2473 chore: remove LXD from group scripts and references - Fixes #283
  build_files/dx/01-install-copr-repos-dx.sh
  just/bluefin-system.just
  system_files/dx/usr/lib/systemd/system/bluefin-dx-groups.service
  system_files/dx/usr/libexec/bluefin-dx-groups
Labels: dx, lgtm, size:XS

#2476 chore: pin iso's to use F41 for installer
  Justfile
Labels: iso, lgtm, size:XS, pin

#2480 revert: "chore: cleanup reusable build ISO"
  .github/workflows/reusable-build-iso.yml
Labels: github_actions, size:L

#2481 chore(ci): update reusable-build-iso.yml
  .github/workflows/reusable-build-iso.yml
Labels: size:XS

#2482 revert: "chore: remove old ISO files"
  .github/workflows/build-iso-gts.yml
  .github/workflows/build-iso-latest.yml
  .github/workflows/build-iso-stable.yml
  .github/workflows/build-isos.yml
Labels: size:M

#2483 chore: name anaconda ISO actions properly
  .github/workflows/build-iso-gts.yml
  .github/workflows/build-iso-latest.yml
  .github/workflows/build-iso-stable.yml
Labels: size:S

#2484 chore(ci): don't build latest ISOs
  .github/workflows/build-isos.yml
Labels: size:XS

#2486 fix(iso): update ISO flatpak list
  bluefin_flatpaks/flatpaks
Labels: size:XS

#2489 chore(iso): build LTS anaconda ISOs
  .github/workflows/build-iso-lts.yml
  Justfile
Labels: iso, size:S

#2490 fix(iso-lts): handle fedora version for Centos
  .github/workflows/build-iso-lts.yml
  Justfile
Labels: iso, lgtm, size:XS

#2498 fix: correctly name live ISOs
  .github/workflows/reusable-build-iso-readymade.yml
Labels: iso, lgtm, size:S

#2499 feat: add branding to the anaconda ISOs (WIP)
  .github/workflows/reusable-build-iso.yml
  Justfile
Labels: iso, size:M

#2503 fix(iso): make sure just is installed correctly + typo fix
  .github/workflows/reusable-build-iso.yml
Labels: size:S

#2508 feat: add gnome firmware flatpak
  bluefin_flatpaks/flatpaks
  iso_files/system-flatpaks.list
  iso_files/system-flatpaks.txt
Labels: enhancement, lgtm, size:M

#2513 chore: remove redundant charm repo
  build_files/base/17-cleanup.sh
  system_files/shared/etc/yum.repos.d/charm.repo
Labels: lgtm, size:XS

#2518 fix: ublue-fix-hostname unit errors
  system_files/shared/usr/lib/systemd/system/ublue-fix-hostname.service
Labels: bug, lgtm, size:XS

#2517 fix: create devmode version directory
  system_files/dx/usr/libexec/bluefin-dx-groups
Labels: dx, lgtm, size:S

#2509 fix: turn on input remapper service on by default
  build_files/base/17-cleanup.sh
Labels: bug, lgtm, size:XS

#2531 fix(iso): Use F41 for ISO
  Justfile
Labels: iso, size:S

#2534 fix(iso): Build arm64 and gdx LTS ISOs
  .github/workflows/build-iso-lts.yml
  .github/workflows/reusable-build-iso.yml
  Justfile
Labels: iso, size:S

#2536 fix(iso): remove arch from flatpaks
  Justfile
  bluefin_flatpaks/flatpaks
  dx_flatpaks/flatpaks
  iso_files/bluefin.repo
Labels: iso, size:M

#2537 feat(iso): Live ISO using anaconda as the installer
  .github/workflows/build-iso-lts.yml
  .github/workflows/reusable-build-iso-anaconda.yml
  iso_files/configure_iso_anaconda.sh
Labels: iso, size:L

#2538 chore(ci): Change Anaconda Live Cloudflare Bucket
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: github_actions, size:S

#2539 fix(iso): anaconda artifact name
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: iso, size:XS

#2543 feat(iso): remove a ton of fonts
  iso_files/configure_iso_anaconda.sh
Labels: iso, lgtm, size:XS

#2541 fix: improve the live anaconda hook
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-latest-hwe.yml
  .github/workflows/build-image-latest-main.yml
  .github/workflows/build-image-stable.yml
  .github/workflows/reusable-build-iso-anaconda.yml
  iso_files/configure_iso_anaconda.sh
Labels: iso, size:L

#2544 fix(iso): push liveCDs to prod
  .github/workflows/reusable-build-iso-anaconda.yml
Labels: iso, lgtm, size:XS

#2551 feat: add bazaar to f42
  packages.json
Labels: enhancement, lgtm, size:XS

#2556 fix: remove old vrr override setting
  system_files/shared/etc/environment
Labels: lgtm, size:XS

#2564 fix: pull in fixed xdg-desktop-portal from fedora
  build_files/base/04-packages.sh
Labels: bug, lgtm, size:XS

#2574 fix(pin): linux-firmware to 20250410
  build_files/base/18-workarounds.sh
Labels: lgtm, size:XS, pin

#2580 fix: update docker extension to container extension
  system_files/dx/usr/share/ublue-os/user-setup.hooks.d/10-vscode.sh
Labels: dx, lgtm, size:XS

#2586 chore: Change VERSION_CODENAME to Deinonychus in /usr/lib/os-release
  build_files/base/00-image-info.sh
Labels: lgtm, size:XS

#2595 fix: disable v42l loopback
  build_files/base/03-install-kernel-akmods.sh
Labels: size:XS

#2594 fix: pin mutter to .48.1-1 in F42
  build_files/base/18-workarounds.sh
Labels: lgtm, size:XS, pin

#2596 revert: "fix: disable v42l loopback"
  build_files/base/03-install-kernel-akmods.sh
Labels: lgtm, size:XS
