Repository ublue-os/bluefin, pull requests merged in 2025-01, with the labels that each got.

#2075 feat: add ignition for startup apps
  bluefin_flatpaks/flatpaks
Labels: enhancement, lgtm, size:XS

#2081 docs: clarify localayering info
  system_files/shared/etc/rpm-ostreed.conf
Labels: documentation, lgtm, size:XS

#2089 chore: add notice about atuin on MOTD
  system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
Labels: lgtm, size:XS

#2090 chore(build-dx): Clean up pretty name in OS release info
  build_files/shared/build-dx.sh
Labels: dx, lgtm, size:XS

#2083 feat(bluefin-cli): add television
  system_files/shared/usr/share/ublue-os/homebrew/bluefin-cli.Brewfile
Labels: enhancement, lgtm, size:XS

#2092 feat: add nvidia-open images
  .github/workflows/build-image-latest.yml
  .github/workflows/build-iso-latest.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  Justfile
  build_files/base/03-install-kernel-akmods.sh
Labels: enhancement, github_actions, lgtm, size:M

#2093 chore(ci): Temporarily disable ISOs
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-latest.yml
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:M

#2096 docs: update motd
  system_files/silverblue/usr/share/ublue-os/motd/bluefin.md
Labels: documentation, lgtm, size:XS

#2097 docs: update readme
  README.md
Labels: size:S

#2098 docs: fix italics
  README.md
Labels: size:XS

#2101 chore: remove unused boot_menu.yml file
  boot_menu.yml
Labels: lgtm, size:S

#2102 fix: add shebang to /usr/bin/sb-key-notify
  system_files/shared/usr/bin/sb-key-notify
Labels: bug, lgtm, size:XS

#2104 fix: pin to 6..8.11 kernel
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
Labels: bug, lgtm, size:XS

#2105 chore: remove systemd unit disable for unknown services on bluefin-dx
  build_files/dx/09-cleanup-dx.sh
Labels: dx, lgtm, size:XS

#2109 fix: ignition flatpak missing arch/branch
  bluefin_flatpaks/flatpaks
Labels: bug, lgtm, size:XS

#2110 fix: artifacthub id
  artifacthub-repo.yml
Labels: size:XS

#2106 fix(actions): try to recover if just fails to install
  .github/workflows/generate-release.yml
  .github/workflows/reusable-build-iso.yml
  .github/workflows/reusable-build.yml
  .github/workflows/shared/install-just.sh
Labels: bug, github_actions, lgtm, size:M

#2113 fix: remove old vestigial file
  system_files/dx/usr/bin/bluefinbox-enter
Labels: lgtm, size:XS

#2114 feat(ci): Enable Docker Building, GHA Log Grouping
  Justfile
  build_files/base/00-image-info.sh
  build_files/base/01-build-fix.sh
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/07-base-image-changes.sh
  build_files/base/08-firmware.sh
  build_files/base/09-hwe-additions.sh
  build_files/base/10-brew.sh
  build_files/base/16-bootc.sh
  build_files/base/17-cleanup.sh
  build_files/base/18-workarounds.sh
  build_files/base/19-initramfs.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/04-override-install-dx.sh
  build_files/dx/09-cleanup-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/build-dx.sh
  build_files/shared/clean-stage.sh
Labels: github_actions, lgtm, size:L

#2115 fix: move powertop to all images
  packages.json
Labels: lgtm, size:XS

#2119 fix(pin): sssd to 2.10
  build_files/base/18-workarounds.sh
Labels: bug, lgtm, size:XS

#2122 fix(pin): pin to kernel 6.11.11
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#2125 revert: "fix(pin): sssd to 2.10"
  build_files/base/18-workarounds.sh
Labels: lgtm, size:XS

#2123 fix(hwe): Fix keyboards on Surface devices
  build_files/base/09-hwe-additions.sh
Labels: lgtm, size:M

#2139 fix: Framework 13 AMD support
  system_files/shared/usr/libexec/ublue-system-setup
Labels: framework, lgtm, size:XS

#2140 fix(just): fix configure-vfio recipe
  just/bluefin-system.just
Labels: bug, lgtm, size:M

#2129 feat: use ublue-motd package for MOTD script
  packages.json
  system_files/shared/usr/libexec/ublue-motd
  system_files/shared/usr/share/fish/vendor_functions.d/fish_greeting.fish
  system_files/shared/usr/share/ublue-os/motd/template.md
  system_files/shared/usr/share/ublue-os/motd/themes/blue.json
  system_files/shared/usr/share/ublue-os/motd/themes/green.json
  system_files/shared/usr/share/ublue-os/motd/themes/orange.json
  system_files/shared/usr/share/ublue-os/motd/themes/pink.json
  system_files/shared/usr/share/ublue-os/motd/themes/purple.json
  system_files/shared/usr/share/ublue-os/motd/themes/red.json
  system_files/shared/usr/share/ublue-os/motd/themes/slate.json
  system_files/shared/usr/share/ublue-os/motd/themes/teal.json
  system_files/shared/usr/share/ublue-os/motd/themes/yellow.json
Labels: enhancement, lgtm, size:XL

#2138 chore: move logos and faces to bluefin-{faces,logos}
  build_files/base/05-override-install.sh
  packages.json
  system_files/silverblue/usr/share/pixmaps/faces/bicycle.jpg
  system_files/silverblue/usr/share/pixmaps/faces/book.jpg
  system_files/silverblue/usr/share/pixmaps/faces/calculator.jpg
  system_files/silverblue/usr/share/pixmaps/faces/cat.jpg
  system_files/silverblue/usr/share/pixmaps/faces/coffee2.jpg
  system_files/silverblue/usr/share/pixmaps/faces/flower2.jpg
  system_files/silverblue/usr/share/pixmaps/faces/gamepad.jpg
  system_files/silverblue/usr/share/pixmaps/faces/guitar2.jpg
  system_files/silverblue/usr/share/pixmaps/faces/headphones.jpg
  system_files/silverblue/usr/share/pixmaps/faces/hummingbird.jpg
  system_files/silverblue/usr/share/pixmaps/faces/mountain.jpg
  system_files/silverblue/usr/share/pixmaps/faces/plane.jpg
  system_files/silverblue/usr/share/pixmaps/faces/surfer.jpg
  system_files/silverblue/usr/share/pixmaps/faces/tomatoes.jpg
  system_files/silverblue/usr/share/pixmaps/faces/tree.jpg
  system_files/silverblue/usr/share/pixmaps/fedora-gdm-logo.png
  system_files/silverblue/usr/share/pixmaps/fedora-logo-small.png
  system_files/silverblue/usr/share/pixmaps/fedora-logo-sprite.png
  system_files/silverblue/usr/share/pixmaps/fedora-logo-sprite.svg
  system_files/silverblue/usr/share/pixmaps/fedora-logo.png
  system_files/silverblue/usr/share/pixmaps/fedora_logo_med.png
  system_files/silverblue/usr/share/pixmaps/fedora_white_logo.svg
  system_files/silverblue/usr/share/pixmaps/fedora_whitelogo.svg
  system_files/silverblue/usr/share/pixmaps/fedora_whitelogo_med.png
  system_files/silverblue/usr/share/pixmaps/system-logo-white.png
Labels: lgtm, size:XS

#2134 chore: use ublue-bling package for bluefin-cli functionality
  build_files/base/18-workarounds.sh
  just/bluefin-system.just
  packages.json
  system_files/shared/etc/ublue-os/bling.json
  system_files/shared/usr/libexec/ublue-bling.sh
  system_files/shared/usr/share/ublue-os/bluefin-cli/bling.fish
  system_files/shared/usr/share/ublue-os/bluefin-cli/bling.sh
Labels: enhancement, lgtm, size:L

#2131 feat: add devcontainer
  .devcontainer/devcontainer.json
  Justfile
Labels: enhancement, lgtm, size:M

#1954 chore: un-cliwrap and use dnf5 instead of rpm-ostree
  Containerfile
  build_files/base/01-build-fix.sh
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/09-hwe-additions.sh
  build_files/base/17-cleanup.sh
  build_files/base/19-initramfs.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/09-cleanup-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/clean-stage.sh
Labels: dx, lgtm, size:L

#2137 chore: remove files provided by bluefin-schemas
  packages.json
  system_files/shared/etc/distrobox/distrobox.conf
  system_files/shared/etc/distrobox/distrobox.example
  system_files/shared/etc/profile.d/askpass.sh
  system_files/shared/etc/profile.d/open.sh
  system_files/shared/etc/skel/.config/toolbox/host-welcome-shown
  system_files/shared/etc/skel/.local/share/flatpak/overrides/com.google.Chrome
  system_files/shared/etc/skel/.local/share/flatpak/overrides/com.visualstudio.code
  system_files/shared/etc/skel/.local/share/org.gnome.Ptyxis/palettes/catppuccin-dynamic.palette
  system_files/shared/etc/skel/.var/app/io.github.dvlv.boxbuddyrs/config/glib-2.0/settings/keyfile
  system_files/shared/usr/share/applications/Discourse.desktop
  system_files/shared/usr/share/applications/system-update.desktop
  system_files/silverblue/etc/dconf/db/distro.d/01-bluefin-folders
  system_files/silverblue/etc/dconf/db/distro.d/02-bluefin-keybindings
  system_files/silverblue/etc/dconf/db/distro.d/03-bluefin-ptyxis-palette
  system_files/silverblue/etc/dconf/db/distro.d/04-bluefin-logomenu-extension
  system_files/silverblue/etc/dconf/db/distro.d/05-bluefin-searchlight-extension
  system_files/silverblue/etc/dconf/db/distro.d/locks/01-bluefin-locked-settings
  system_files/silverblue/usr/share/applications/documentation.desktop
Labels: lgtm, size:L

#2135 chore: move homebrew configuration to ublue-brew
  packages.json
  system_files/shared/etc/profile.d/brew-bash-completion.sh
  system_files/shared/etc/security/limits.d/30-brew-limits.conf
  system_files/shared/usr/lib/systemd/system-preset/02-homebrew-update.preset
  system_files/shared/usr/lib/systemd/system/brew-setup.service
  system_files/shared/usr/lib/tmpfiles.d/homebrew.conf
  system_files/shared/usr/share/fish/vendor_conf.d/brew.fish
Labels: brew, lgtm, size:M

#2128 feat: move fastfetch config (and logos) to COPR package
  packages.json
  system_files/shared/etc/profile.d/neofetch.sh
  system_files/shared/etc/ublue-os/fastfetch.json
  system_files/shared/usr/libexec/ublue-bling-fastfetch
  system_files/shared/usr/share/fish/vendor_conf.d/neofetch.fish
  system_files/shared/usr/share/ublue-os/ublue-os.jsonc
  system_files/silverblue/etc/fish/conf.d/bluefin-fastfetch.fish
  system_files/silverblue/etc/profile.d/bluefin-fastfetch.sh
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/bluefin.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/chicken.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/dolly.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/karl.png
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/bluefin
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/chicken
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/dolly
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/sixels/karl
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/bluefin
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/chicken
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/dolly
  system_files/silverblue/usr/share/ublue-os/bluefin-logos/symbols/karl
Labels: enhancement, lgtm, size:L

#2142 revert: "chore: un-cliwrap and use dnf5 instead of rpm-ostree"
  Containerfile
  build_files/base/01-build-fix.sh
  build_files/base/02-install-copr-repos.sh
  build_files/base/03-install-kernel-akmods.sh
  build_files/base/04-packages.sh
  build_files/base/05-override-install.sh
  build_files/base/09-hwe-additions.sh
  build_files/base/17-cleanup.sh
  build_files/base/19-initramfs.sh
  build_files/dx/01-install-copr-repos-dx.sh
  build_files/dx/02-install-kernel-akmods-dx.sh
  build_files/dx/03-packages-dx.sh
  build_files/dx/09-cleanup-dx.sh
  build_files/shared/build-base.sh
  build_files/shared/clean-stage.sh
Labels: size:L

#2146 pin: kernel back to 6.11.8
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
Labels: github_actions, lgtm, size:XS

#2148 fix: remove sudo from ublue-system-setup
  system_files/shared/usr/lib/systemd/system/ublue-system-setup.service
  system_files/shared/usr/libexec/ublue-system-setup
Labels: bug, lgtm, size:XS

#2153 fix: just formatting updated on version 1.39
  Justfile
  build_files/base/09-hwe-additions.sh
Labels: lgtm, size:S

#2151 fix(artifacthub): remove artifacthub category
  Justfile
Labels: lgtm, size:XS

#2161 chore(ci): delete .github/dependabot.yml
  .github/dependabot.yml
Labels: lgtm, size:S

#2168 feat: update bluefin stable kernel pin to 6.12.9
  .github/workflows/build-image-gts.yml
  .github/workflows/build-image-stable.yml
  Justfile
Labels: enhancement, lgtm, size:S

#2171 feat: add automatic wallpaper changing by month from achillobator
  build_files/base/05-override-install.sh
Labels: enhancement, lgtm, size:XS

#2163 fix: allow wheel users to access yubikeys
  system_files/shared/usr/share/polkit-1/rules.d/99-pcscd.rules
Labels: lgtm, size:S
